poetry_requirements(
    name="poetry",
    resolve="app1"
)
python_sources(name="lib2", resolve="app1", sources=["lib2/**/*.py"])
python_tests(name="lib2_tests", resolve="app1", sources=["tests/**/test_*.py"])
