name: Build Stable Release

on:
  release:
    types:
      - published
      - edited

jobs:
  build:
    name: Perform build and package operations
    env:
      PANTS_CONFIG_FILES: pants.ci.toml
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: cache
      with:
        path: |
          ~/.cache/pants/setup
          ~/.cache/pants/lmdb_store
          ~/.cache/pants/named_caches
        key: ${{ runner.os }}-
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Bootstrap Pants
      run: |
        ./pants --version
    - name: Check BUILD files
      run: ./pants tailor --check update-build-files --check
    - name: Package
      run: |
        ./pants --changed-since=origin/main --changed-dependees=transitive package
    - name: Publish
      run: |
        export GIT_COMMIT=$(git rev-parse --short HEAD)
        export VERSION=rc-$GIT_COMMIT
        export TYPE=rc
        ./pants --changed-since=origin/main --changed-dependees=transitive package
